import './globals.css'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'CyberDog (change name)',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen container mx-auto bg-background flex flex-col items-center">
          <Theme className='w-full'>
            {children}
          </Theme>
          
        <Toaster />
        </main>
      </body>
    </html>
  )
}
