import './globals.css'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen container mx-auto bg-background flex flex-col items-center">
          <Theme className='w-full'>
            {children}
          </Theme>
        </main>
      </body>
    </html>
  )
}
